### ISSUE TITLE
approve_dai() got an unexpected keyword argument 'gas_price' from `deployment.py:335`

### ISSUE THREAD

**Issue by bneiluj** [makerdao/auction-keeper#50]
Function `lib/pymaker/pymaker/deployment.py:335:    def approve_dai(self, usr: Address, **kwargs):` is not defined to take `gas_price` parameter. 

```
2020-03-18 10:14:35,585 INFO     Current gas prices information from 'ethgasstation.info' became available
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/MakerDAO/auction-keeper/auction_keeper/main.py", line 580, in <module>
    AuctionKeeper(sys.argv[1:]).main()
  File "/home/ubuntu/MakerDAO/auction-keeper/auction_keeper/main.py", line 224, in main
    lifecycle.every(self.arguments.bid_check_interval, self.check_for_bids)
  File "/opt/keeper/auction-keeper/lib/pymaker/pymaker/lifecycle.py", line 149, in __exit__
    self.startup_function()
  File "/home/ubuntu/MakerDAO/auction-keeper/auction_keeper/main.py", line 227, in startup
    self.approve()
  File "/home/ubuntu/MakerDAO/auction-keeper/auction_keeper/main.py", line 241, in approve
    self.mcd.approve_dai(usr=self.our_address, gas_price=self.gas_price)
TypeError: approve_dai() got an unexpected keyword argument 'gas_price'
```

**Comment by EdNoepel** [comment]
In case anyone else hits this, solution was to `git submodule update --recursive` to pull down an updated `pymaker`.

**Comment by bneiluj** [comment]
@EdNoepel it doesn't solve the issue. Even with fresh install.

**Comment by bneiluj** [comment]
Even using latest commit from `pymaker` edf4b52aa43012d130b22672dfe21878ebbee753
```
(_virtualenv) ubuntu@ip-10-0-0-130:~/MakerDAO/auction-keeper$ git submodule update --init --recursive --force
Submodule path 'lib/ethgasstation-client': checked out '76b96626528d63e7b64b43615811c86ad1c99138'
Submodule path 'lib/pymaker': checked out 'edf4b52aa43012d130b22672dfe21878ebbee753'
(_virtualenv) ubuntu@ip-10-0-0-130:~/MakerDAO/auction-keeper$ grep -nr "approve_dai" lib/
lib/pymaker/tests/manual_test_mcd.py:55:    mcd.approve_dai(our_address)
lib/pymaker/tests/test_savings.py:58:    mcd.approve_dai(dsr.owner)
lib/pymaker/tests/test_auctions.py:191:        mcd.approve_dai(deployment_address)
lib/pymaker/tests/test_auctions.py:400:        mcd.approve_dai(our_address)
lib/pymaker/tests/test_dss.py:160:    mcd.approve_dai(address)
lib/pymaker/tests/test_dss.py:607:        mcd.approve_dai(our_address)
lib/pymaker/README.md:239:mcd.approve_dai(our_address)
lib/pymaker/pymaker/deployment.py:335:    def approve_dai(self, usr: Address, **kwargs):
```
